---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: ストレージデータを移行する際、ストレージバックエンドはREST APIを使用して手動でオンボーディングされます。VASA Providerのデータを移行すると、既存のDerbyデータベースからデータがエクスポートされ、MongoDBデータベースにインポートされます。 
---
= VASA プロバイダーを移行し、SRA を更新する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




[[steps-to-migrate-the-vasa-provider]]
== VASAプロバイダーの移行手順

. 既存のONTAP tools for VMware vSphereでDerbyポート1527を有効にするには、rootユーザを有効にし、SSHを使用してCLIにログインします。次に、次のコマンドを実行します。
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. ONTAP tools for VMware vSphere 10.3向けOVAを導入します。
. 移行するvCenter ServerインスタンスをONTAP tools for VMware vSphere 10.3リリースに追加します。詳細については、を参照してください link:../configure/add-vcenter.html["vCenter Serverインスタンスを追加する"] 。
. ONTAP ツール プラグインの vCenter Server API からストレージ バックエンドをローカルにオンボードします。
. SwaggerまたはPostmanから次のAPIを実行して移行します。
+
カール- Xポスト https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs[]

+
Swaggerには、次のURLからアクセスできます。https://$FQDN_IP_PORT/,例： https://10.67.25.33:8443/[]

+
[]
====
* HTTPメソッドとエンドポイント*

このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

|===


| * HTTP メソッド * | * パス * 


| 投稿 | /api/v1 
|===
*処理タイプ*

非同期

*カールの例*

カール -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs'[] \ --header 'x-auth: <認証トークン>' \ --header 'Content-Type: application/json' \ --data '{ "otv_ip": "xx.xx.xx.xx", "vasa_provider_credentials": { "username": "xxxxx", "password": "******" }, "database_password": "******" }'

他のリリース移行のリクエスト本文：

{ "otv_ip": "xx.xx.xx.xx", "vasa_provider_credentials": { "ユーザー名": "xxxxx", "パスワード": "*******" } }

* JSON出力例*

ジョブオブジェクトが返されます。次の手順で使用するには、ジョブIDを保存する必要があります。

｛"id"：123、"migration_id"："d50073ce-35b4-4c51-9d2e-4ce66f802c35"、"status"："running"｝

====
. Swaggerで次のURIを使用してステータスを確認します。
+
[listing]
----
curl https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true
----
+
ジョブが完了したら、移行レポートを確認します。このレポートはジョブデータに含まれており、ジョブ応答からアクセスできます。

. VMware vSphereストレージプロバイダ用のONTAPツールをvCenter Serverに追加し、 link:../configure/registration-process.html["VASA Providerを登録する"] VMware vSphere 用の ONTAP ツールを使用します。
. link:../manage/enable-services.html["VASA Provider の有効化"]Service on ONTAP tools for VMware vSphere 10.3を参照してください。
. ONTAP Tools for VMware vSphereストレージプロバイダ9.10 / 9.11 / 9.12 / 9.13 VASA Providerサービスをメンテナンスコンソールから停止します。
+
VASA Providerは削除しないでください。

+
古いVASA Providerを停止すると、vCenter ServerはONTAP tools for VMware vSphereにフェイルオーバーします。すべてのデータストアとVMにアクセスし、ONTAP Tools for VMware vSphereからアクセスできます。

. ONTAP tools for VMware vSphere 9.xxxから移行されたNFSデータストアとVMFSデータストアがONTAP tools for VMware vSphere 10.3に表示されるのは、データストアの検出ジョブがトリガーされてからで、完了までに最大30分かかることがあります。VMware vSphere プラグインのユーザー インターフェイス ページの ONTAP ツールの概要ページにデータストアが表示されていることを確認します。
. SwaggerまたはPostmanで次のAPIを使用してパッチの移行を実行します。
+
[]
====
* HTTPメソッドとエンドポイント*

このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

|===


| * HTTP メソッド * | * パス * 


| パッチ | /api/v1 
|===
*処理タイプ*

非同期

*カールの例*

CURL-Xパッチ https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/84dr73bd-9173-65r7-w345-8ufdbb887d43[]

* JSON出力例*

ジョブオブジェクトが返されます。次の手順で使用するには、ジョブIDを保存する必要があります。

｛"id"：123、"migration_id"："d50073ce-35b4-4c51-9d2e-4ce66f802c35"、"status"："running"｝

PATCH処理の要求の本文が空です。


NOTE: UUIDは、移行後のAPIに対する応答で返される移行UUIDです。

パッチ移行APIを実行すると、すべてのVMがストレージポリシーに準拠します。

====


.次の手順
移行を完了してONTAP tools 10.3をvCenter Serverに登録したら、次の手順を実行します。

* 検出*が完了するまで待ちます。証明書はすべてのホストで自動的に更新されます。
* データストアと仮想マシンの処理を開始する前に十分な時間を確保してください。必要な待機時間は、構成内のホスト、データストア、および仮想マシンの数によって異なります。待機しないと、一時的に動作エラーが発生する可能性があります。


アップグレード後に仮想マシンのコンプライアンス状態が古い場合は、次の手順に従ってストレージポリシーを再適用します。

. データストアに移動し、*[概要]*>*[ VMストレージポリシー]*を選択します。
+
[VM storage policy compliance]*で、準拠ステータスが* out-of-date *と表示されます。

. Storage VMポリシーと対応するVMを選択してください
. [適用]を選択します。
+
[VM storage policy compliance]*で、準拠ステータスが[準拠]と表示されるようになりました。



.関連情報
* link:../concepts/rbac-learn-about.html["ONTAP Tools for VMware vSphere 10 RBACの詳細"]
* link:../upgrade/upgrade-ontap-tools.html["ONTAP Tools for VMware vSphere 10.xから10.3へのアップグレード"]




[[steps-to-update-the-storage-replication-adaptorsra]]
== ストレージレプリケーションアダプタ(SRA)を更新する手順

.開始する前に
リカバリプランにおいて、保護サイトとは仮想マシンが現在実行されている場所を指し、リカバリサイトとは仮想マシンがリカバリされる場所を指します。SRMインターフェースには、リカバリプランの状態と、保護サイトとリカバリサイトの詳細が表示されます。リカバリプランでは、「クリーンアップ」ボタンと「再保護」ボタンは無効になっていますが、「テスト」ボタンと「実行」ボタンは有効なままです。これは、サイトがデータリカバリの準備ができていることを示します。SRAを移行する前に、一方のサイトが保護状態、もう一方のサイトがリカバリ状態であることを確認してください。


NOTE: フェイルオーバーが完了しても再保護が保留中の場合は、移行を開始しないでください。移行を続行する前に、再保護プロセスが完了していることを確認してください。テストフェイルオーバーを実行中の場合は、テストフェイルオーバーをクリーンアップして移行を開始します。

. VMware Site RecoveryでONTAP tools SRAアダプタfor VMware vSphere 9.xxを削除するには、次の手順を実行します。
+
.. VMware Live Site Recovery構成管理ページに移動します。
.. Storage Replication Adapter *セクションに移動します。
.. 省略記号メニューから* Reset configuration *を選択します。
.. 省略記号メニューから*削除*を選択します。


. これらの手順は、保護サイトとリカバリサイトの両方で実行します。
+
.. の手順に従って、ONTAP Tools for VMware vSphere 10.3 SRAアダプタをインストールしますlink:../protect/configure-on-srm-appliance.html["VMware Live Site RecoveryアプライアンスでのSRAの設定"]。
.. VMware Live Site Recoveryのユーザーインターフェイスページで、*アレイの検出*および*デバイスの検出*操作を実行し、移行前と同じようにデバイスが表示されることを確認します。



