---
permalink: protect/configure-storage-replication-adapter-for-highly-scaled-environment.html 
sidebar: sidebar 
keywords:  
summary: 大規模な環境で最適なパフォーマンスを実現するには、Storage Replication Adapter（SRA\）の推奨設定に従ってストレージのタイムアウト間隔を設定する必要があります。 
---
= 大規模な環境向けのSRAの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
大規模な環境で最適なパフォーマンスを実現するには、Storage Replication Adapter（SRA）の推奨設定に従ってストレージのタイムアウト間隔を設定する必要があります。



== ストレージプロバイダの設定

大規模な環境では、VMware Live Site Recoveryで次のタイムアウト値を設定する必要があります。

|===


| * 詳細設定 * | * タイムアウト値 * 


 a| 
`StorageProvider.resignatureTimeout`
 a| 
設定値を900秒から12000秒に増やします。



 a| 
`storageProvider.hostRescanDelaySec`
 a| 
60



 a| 
`storageProvider.hostRescanRepeatCnt`
 a| 
20



 a| 
`storageProvider.hostRescanTimeoutSec`
 a| 
高い値を設定します（例：99999）。

|===
また、 `StorageProvider.autoResignatureMode`オプションを有効にする必要があります。

ストレージプロバイダの設定の変更の詳細については、を参照してください https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/how-do-i-protect-my-environment/advanced-srm-configuration/reconfigure-srm-settings/change-storage-provider-settings.html["Change Storage Provider Settings"]。



== ストレージ設定

タイムアウトになった場合は `storage.commandTimeout`、との値を大きくして `storage.maxConcurrentCommandCnt`大きい値にします。


NOTE: 指定するタイムアウト間隔は最大値です。最大タイムアウトに達することはありません。ほとんどのコマンドは、設定された最大タイムアウト間隔内で終了します。

SANプロバイダ設定の変更については、を参照してください https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/how-do-i-protect-my-environment/advanced-srm-configuration/reconfigure-srm-settings/change-storage-settings.html["Change Storage Settings"]。
