---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: 保護対象サイトで仮想マシンのグループを保護するには、保護グループを作成する必要があります。 
---
= 保護対象サイトとリカバリサイトの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
保護対象サイトで仮想マシンのグループを保護するには、保護グループを作成する必要があります。



== 保護グループの設定

.開始する前に
ソースサイトとターゲットサイトの両方が次のように構成されていることを確認する必要があります。

* 同じバージョンのVMware Live Site Recoveryがインストールされている
* 仮想マシン
* 保護対象サイトとリカバリサイトをペアリング
* ソースとデスティネーションのデータストアがそれぞれのサイトにマウントされていること


.手順
. vCenter Serverにログインし、*[サイトリカバリ]*>*[保護グループ]*を選択します。
. [保護グループ]*ペインで*[新規]*を選択します。
. 保護グループの名前と説明、方向を指定し、* Next *を選択します。
. [タイプ]*フィールドで、NFSおよびVMFSデータストアの[タイプ]フィールドオプション...*を[データストアグループ（アレイベースのレプリケーション）]として選択します。フォールトドメインは、レプリケーションが有効になっているSVMにすぎません。ピアリングのみが実装されていて問題がないSVMが表示されます。
. Replication groups（レプリケーショングループ）タブで、有効なアレイペアまたは設定した仮想マシンがあるレプリケーショングループのいずれかを選択し、* Next（次へ）*を選択します。
+
レプリケーショングループ上のすべての仮想マシンが保護グループに追加されます。

. 既存のリカバリプランを選択するか、*[新しいリカバリプランに追加]*を選択して新しいプランを作成します。
. [Ready to Complete]タブで、作成した保護グループの詳細を確認し、*[Finish]*を選択します。




== 保護対象サイトとリカバリサイトをペアリング

Storage Replication Adapter（SRA）でストレージシステムを検出できるようにするには、作成された保護対象サイトとリカバリサイトをvSphere Clientを使用してペアリングする必要があります。

.開始する前に
* 保護対象サイトとリカバリサイトにVMware Live Site Recoveryがインストールされている必要があります。
* 保護対象サイトとリカバリサイトにSRAをインストールしておく必要があります。


.手順
. vSphere Clientのホームページで* Site Recovery *をダブルクリックし、* Sites *を選択します。
. [オブジェクト]*>*[アクション]*>*[サイトのペアリング]*を選択します。
. [Site Recovery Managerサーバのペアリング]ダイアログボックスで、保護対象サイトのプラットフォームサービスコントローラのアドレスを入力し、*[次へ]*を選択します。
. [vCenter Serverの選択]セクションで、次の手順を実行します。
+
.. 保護対象サイトのvCenter Serverが対応するペア候補として表示されることを確認します。
.. SSO管理クレデンシャルを入力し、*[終了]*を選択します。


. プロンプトが表示されたら、*[はい]*を選択してセキュリティ証明書を受け入れます。


.結果
保護対象サイトとリカバリサイトの両方が [ オブジェクト ] ダイアログボックスに表示されます。
