---
permalink: protect/configure-array-manager.html 
sidebar: sidebar 
keywords:  
summary: VMware Live Site RecoveryのArray Managerウィザードを使用してStorage Replication Adapter（SRA\）を設定し、VMware Live Site RecoveryとStorage Virtual Machine（SVM\）が連携できるようにすることができます。 
---
= アレイマネージャを使用したSRAの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware Live Site RecoveryのArray Managerウィザードを使用してStorage Replication Adapter（SRA）を設定し、VMware Live Site RecoveryとStorage Virtual Machine（SVM）の間のやり取りを有効にすることができます。

.開始する前に
* VMware Live Site Recoveryで保護対象サイトとリカバリサイトをペアリングしておく必要があります。
* アレイマネージャを設定する前に、オンボードストレージを設定しておく必要があります。
* 保護対象サイトとリカバリサイト間のSnapMirror関係を設定し、レプリケートしておく必要があります。
* マルチテナンシーを有効にするには、SVM管理LIFを有効にしておく必要があります。


SRAでは、クラスタレベルの管理とSVMレベルの管理がサポートされます。クラスタレベルでストレージを追加すると、クラスタ内のすべてのSVMを検出して処理を実行できます。SVMレベルでストレージを追加する場合は、そのSVMのみを管理できます。

.手順
. VMware Live Site Recoveryで、* Array Managers *>* Add Array Manager *を選択します。
. 次の情報を入力して、VMware Live Site Recoveryでアレイについて説明します。
+
.. [*Display Name*] フィールドに、アレイマネージャを識別する名前を入力します。
.. 「 * SRA Type * 」フィールドで、「 * ONTAP 向け NetApp Storage Replication Adapter 」を選択します。
.. クラスタまたはSVMへの接続情報を入力します。
+
*** クラスタに接続する場合は、クラスタ管理LIFを入力する必要があります。
*** SVM に直接接続する場合は、 SVM 管理 LIF の IP アドレスを入力する必要があります。
+

NOTE: アレイマネージャを設定するときは、ONTAP tools for VMware vSphereでストレージシステムのオンボードに使用したのと同じ接続（IPアドレス）をストレージシステムに使用する必要があります。たとえば、アレイマネージャの設定範囲がSVMである場合は、ONTAP tools for VMware vSphereのストレージをSVMレベルで追加する必要があります。



.. クラスタに接続する場合は、 SVM の名前を * SVM 名 * フィールドに入力します。
+
このフィールドは空白のままにすることもできます。

.. 検出するボリュームを * Volume include list * フィールドに入力します。
+
保護対象サイトのソースボリュームとリカバリサイトのレプリケートされたデスティネーションボリュームを入力できます。

+
たとえば、ボリュームdst_vol1とSnapMirror関係にあるボリュームsrc_vol1を検出する場合は、保護対象サイトのフィールドでsrc_vol1を指定し、リカバリサイトのフィールドでdst_vol1を指定する必要があります。

.. * （オプション） * Volume exclude list * フィールドに、検出対象から除外するボリュームを入力します。
+
保護対象サイトのソースボリュームとリカバリサイトのレプリケートされたデスティネーションボリュームを入力できます。

+
たとえば、volume_dst_vol1_とSnapMirror関係にあるvolume_src_vol1_を除外する場合は、保護対象サイトのフィールドで_src_vol1_を指定し、リカバリサイトのフィールドで_dst_vol1_を指定する必要があります。



. 「 * 次へ * 」を選択します。
. アレイが検出され、[Add Array Manager]ウィンドウの下部に表示されていることを確認し、*[Finish]*を選択します。


適切なSVM管理IPアドレスとクレデンシャルを使用して、リカバリサイトでも同じ手順を実行します。Add Array ManagerウィザードのEnable Array Pairs（アレイペアの有効化）画面で、正しいアレイペアが選択され、有効にする準備ができていることを確認します。
