---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphereは、NetAppストレージシステムに最適なESXiホストのマルチパス設定とHBAタイムアウト設定を確認して設定します。 
---
= ESXiホストの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ESXiサーバのマルチパスとタイムアウトを設定すると、プライマリパスに障害が発生した場合にバックアップストレージパスにシームレスに切り替えることができるため、高可用性とデータの整合性が確保されます。



== ESXiサーバのマルチパスとタイムアウトの設定

ONTAP tools for VMware vSphereは、NetAppストレージシステムに最適なESXiホストのマルチパス設定とHBAタイムアウト設定を確認して設定します。

* このタスクについて *

構成とシステムの負荷によっては、このプロセスに時間がかかることがあります。タスクの進行状況は、[最近のタスク]パネルに表示されます。

.手順
. VMware vSphere Web Clientのホームページで、*[ホストおよびクラスタ]*を選択します。
. ホストを右クリックし、* NetApp ONTAP tools *>* Update host data *を選択します。
. VMware vSphere Web Clientのショートカットページで、[plug-ins]セクションで* NetApp ONTAP tools *を選択します。
. ONTAP Tools for VMware vSphereプラグインの概要（ダッシュボード）にある* ESXiホストコンプライアンス*カードに移動します。
. [推奨設定の適用]*リンクを選択します。
. [推奨されるホスト設定を適用]*ウィンドウで、NetAppの推奨設定に準拠するように更新するホストを選択し、*[次へ]*を選択します。
+

NOTE: ESXiホストを展開すると、現在の値を確認できます。

. 設定ページで、必要に応じて推奨値を選択します。
. 概要ペインで値を確認し、*[完了]*を選択します。進捗状況は、最近のタスクパネルで追跡できます。




== ESXiホストの値の設定

ONTAP tools for VMware vSphereを使用すると、ESXiホストでタイムアウトなどの値を設定して、最適なパフォーマンスが確保され、フェイルオーバーが正常に実行されるようにすることができます。ONTAP tools for VMware vSphereが設定する値は、社内のNetAppテストに基づいています。

ESXiホストで設定できる値は次のとおりです。



=== HBA / CNAアダプタ設定

次のパラメータをデフォルト値に設定します。

* Disk.QFullSampleSize
* Disk.QFullThreshold
* Emulex FC HBAタイムアウト
* QLogic FC HBAタイムアウト




=== MPIO設定

MPIO設定では、NetAppストレージシステムの優先パスを定義します。また、使用可能なパスのうちどのパスが最適化されているか（インターコネクトケーブルを経由する非最適化パスではなく）が判断され、そのいずれかのパスに優先パスが設定されます。

ハイパフォーマンス環境や、単一のLUNデータストアでパフォーマンスをテストする場合は、ラウンドロビン（VMW_PSP_RR）パス選択ポリシー（PSP）の負荷分散設定をデフォルトのIOPS設定である1000から1に変更することを検討してください。



=== NFS設定

|===


| パラメータ | 設定する値 


| Net.TcpipHeapSize | 32 


| Net.TcpipHeapMax | 1024 MB 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128以上 


| NFS.HeartbeatMaxFailures | 10 


| NFS.HeartbeatFrequency | 12 


| NFS.HeartbeatTimeout | 5 
|===