---
permalink: configure/registration-process.html 
sidebar: sidebar 
keywords:  
summary: VASA Providerは、ONTAP tools for VMware vSphereリモートプラグインインターフェイスを使用してvCenter Serverインスタンスに登録できます。 
---
= VASA ProviderをvCenter Serverインスタンスに登録する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VASA Providerは、ONTAP tools for VMware vSphereを使用してvCenter Serverインスタンスに登録できます。[VASA Providerの設定]セクションに、選択したvCenter ServerのVASA Providerの登録ステータスが表示されます。

.手順
. vSphere Clientにログインします。
. プラグインセクションで*ショートカット*>* NetApp ONTAP tools *を選択します。
. [設定]*>*[VASA Provider設定]*を選択します。VASA Providerの登録ステータスは「Not Registered」と表示されます。
. [登録]*ボタンを選択してVASA Providerを登録します。
. VASA Providerの名前を入力し、ONTAP tools for VMware vSphereアプリケーションのユーザクレデンシャルを指定して、*[登録]*を選択します。
. 登録が完了してページが更新されると、登録されているVASA Providerのステータス、名前、バージョンが表示されます。登録後、登録解除アクションがアクティブになります。


* 終了後 *

vCenterクライアントからオンボードしたVASA Providerが[VASA Provider]の下に表示されていることを確認します。

.手順
. vCenter Serverインスタンスに移動します。
. 管理者のクレデンシャルでログインします。
. [ストレージプロバイダ]*>*[設定]*を選択します。オンボードしたVASA Providerが正しく表示されていることを確認します。

