---
permalink: manage/delete-ds.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: Delete datastore action：データストアを削除します。NFSまたはVMFSデータストアの場合は、ダイアログボックスに、そのデータストアを使用しているVMのリストが表示されます。 
---
= データストアの削除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[データストアからのストレージの削除]操作は、vCenter Serverで検出または管理されるすべてのONTAP tools for VMware vSphere vVolデータストアでサポートされます。この操作により、vVolデータストアからボリュームを削除できます。

削除オプションは、特定のボリュームにVVolがある場合は無効になります。データストアからのボリュームの削除に加えて、ONTAPストレージ上の選択したボリュームも削除できます。

vCenter ServerのONTAP tools for VMware vSphereからデータストアを削除すると、次の処理が実行されます。

* VVolコンテナをアンマウントします。
* igroupをクリーンアップします。igroupを使用していない場合は、iqnをigroupから削除します。
* VVolコンテナを削除します。
* Flexボリュームをストレージアレイに残します。


vCenter ServerからONTAP toolsからNFS、VMFS、またはVVolデータストアを削除するには、次の手順を実行します。

.手順
. vSphere Clientにログインします。
. ホストシステム、ホストクラスタ、データセンターを右クリックし、* NetApp ONTAP tools *>*データストアの削除*を選択します。
+

NOTE: データストアを使用している仮想マシンがある場合は、データストアを削除できません。データストアを削除する前に、仮想マシンを別のデータストアに移動する必要があります。データストアが保護されたホストクラスタに属している場合、[ボリュームの削除]チェックボックスは選択できません。

+
.. NFSまたはVMFSデータストアの場合は、ダイアログボックスに、そのデータストアを使用しているVMのリストが表示されます。
.. VMFSデータストアがASA R2システムで作成され、保護の一部である場合は、データストアを削除する前に保護を解除する必要があります。
.. vVolデータストアの場合、[Delete datastore]操作を実行すると、関連付けられているvVolがないデータストアのみが削除されます。[Delete datastore]ダイアログボックスには、ONTAPクラスタからボリュームを削除するオプションがあります。
.. ASA R2システムベースのvVolデータストアの場合、元のボリュームを削除するチェックボックスは適用されません。


. ONTAPストレージの元のボリュームを削除するには、* ONTAPクラスタのボリュームを削除する*を選択します。
+

NOTE: 保護対象ホストクラスタに含まれているVMFSデータストアのONTAPクラスタ上のボリュームは削除できません。


