---
permalink: manage/enable-backup.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphere 10.3では動的ストレージプロビジョニングツールが使用されるため、RPOをゼロにすることはできません。ただし、RPOはほぼゼロに近づきます。 
---
= バックアップの作成とセットアップのリカバリ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere 10.3では動的ストレージプロビジョニングツールが使用されるため、RPOゼロを達成することはできません。ただし、RPOはほぼゼロに近づきます。RPOをほぼゼロにするには、セットアップのバックアップを作成し、新しい仮想マシンにリストアする必要があります。



== バックアップを作成し、バックアップファイルをダウンロードする

.手順
. vCenter Serverで、メンテナンスコンソールを開きます。
. maintenanceユーザとしてログインします。
. と入力 `4`して*[Support and Diagnostics]*を選択します。
. と入力 `3`して*[システムバックアップを有効にする]*オプションを選択します。
. HA構成でない場合は、ONTAP tools仮想マシンが導入されているvCenterクレデンシャルを入力します。
. バックアップ頻度の値を5~60分で入力します。
. Enter*キーを押します。
+
これにより、バックアップが作成され、一定の間隔で仮想マシンのデータストアにバックアップがプッシュされます。

. バックアップにアクセスするには、[Storage]セクションに移動して仮想マシンのデータストアを選択します。
. [ファイル]*セクションを選択します。
+
ファイルセクションでは、ディレクトリが表示されます。ディレクトリの名前は、ONTAP toolsのIPアドレスになります。ドット（.）は、_backup_というサフィックス付きのアンダースコアに置き換えられます。

. バックアップの詳細については、* Files *>* Download *からbackup_info.txtファイルをダウンロードしてください。




== リカバリ

セットアップをリカバリするには、既存の仮想マシンの電源をオフにし、初期導入で使用したOVAを使用して新しい仮想マシンを導入します。

新しい仮想マシンには同じONTAP toolsのIPアドレス（ロードバランサIP）を使用する必要があります。また、サービスが有効になっている、ノードサイズ、HAモードなどのシステム構成は、初期導入時と同じにする必要があります。

バックアップファイルからセットアップをリカバリするには、次の手順を実行します。

. vCenter Serverで、メンテナンスコンソールを開きます。
. maintenanceユーザとしてログインします。
. と入力 `4`して*[Support and Diagnostics]*を選択します。
. と入力 `2`して*[リモート診断アクセスを有効にする]*オプションを選択し、診断アクセス用の新しいパスワードを作成します。
. ダウンロードしたディレクトリからバックアップを1つ選択します。最後のバックアップファイル名は_backup_info.txt_fileに記録されます。
. 次のコマンドを実行してバックアップを新しい仮想マシンにコピーし、プロンプトが表示されたら診断パスワードを入力します。
+
[listing]
----
scp <Backup_X.tar.enc> diag@<node_ip>:/home/diag/system_recovery.tar.enc
----
+

NOTE: コマンドに記載されている宛先パスとファイル名（/home/diag/system_recovery.tar.enc）は変更しないでください。

. バックアップファイルがコピーされたら、診断シェルにログインし、次のコマンドを実行します。
+
[listing]
----
sudo perl /home/maint/scripts/post-deploy-upgrade.pl -recovery
----
+
ログは_/ var/log/post-deploy-upgrade.log_fileに記録されます。

. リカバリが成功すると、サービスとvCenterオブジェクトがリストアされます。

