---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: データセンター内の既存の仮想マシンを移行する際の考慮事項について理解しておく必要があります。 
---
= 仮想マシンの移行またはクローニングに関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データセンター内の既存の仮想マシンを移行する際には、いくつかの考慮事項を理解しておく必要があります。



== 保護された仮想マシンの移行

保護された仮想マシンを次の場所に移行できます。

* 同じvVolデータストアが別のESXiホストにある
* 同じESXiホストにある互換性のある異なるvVolデータストア
* 別のESXiホストにある互換性のある異なるvVolデータストア


仮想マシンを別のFlexVolボリュームに移行すると、対応するメタデータファイルも仮想マシンの情報で更新されます。仮想マシンを同じストレージの別のESXiホストに移行した場合、基盤となるFlexVolボリュームメタデータファイルは変更されません。



== 保護対象の仮想マシンのクローン作成

保護された仮想マシンのクローンは、次の場所に作成できます。

* レプリケーショングループを使用する同じFlexVol volumeの同じコンテナ
+
同じFlexVol volumeのメタデータファイルが、クローニングされた仮想マシンの詳細で更新されます。

* レプリケーショングループを使用する別のFlexVol volumeの同じコンテナ
+
クローニングされた仮想マシンが配置されているFlexVol volumeで、メタデータファイルがクローニングされた仮想マシンの詳細で更新されます。

* 別のコンテナまたはvVolデータストア
+
クローニングされた仮想マシンが配置されているFlexVol volumeでは、メタデータファイルによって更新された仮想マシンの詳細が取得されます。



VMwareでは、現在、VMテンプレートにクローニングされた仮想マシンはサポートされていません。

保護された仮想マシンのクローン作成がサポートされています。

詳細については、を参照してください https://docs.vmware.com/en/VMware-Horizon/2103/virtual-desktops/GUID-B5020738-8649-4308-A8B0-70AF80527DF6.html["クローニング用仮想マシンの作成"]。



== 仮想マシンのスナップショット

現時点では、メモリのない仮想マシンのスナップショットのみがサポートされています。仮想マシンにメモリ付きのSnapshotがある場合、仮想マシンは保護対象とはみなされません。

また、メモリスナップショットを持つ保護されていない仮想マシンを保護することもできません。このリリースでは、仮想マシンの保護を有効にする前に、メモリスナップショットを削除する必要があります。

ストレージタイプがASA R2のWindows VMの場合、仮想マシンのスナップショットを作成すると、そのスナップショットは読み取り専用スナップショットになります。VMの電源投入が発生すると、VASA Providerは読み取り専用Snapshotを使用してLUNを作成し、IOPSに対してそのLUNを有効にします。電源オフ要求時に、作成されたLUNがVASA Providerによって削除され、IOPSが無効になります。
