---
permalink: manage/storage-backend.html 
sidebar: sidebar 
keywords:  
summary: ストレージバックエンドは、ESXiホストがデータストレージに使用するシステムです。 
---
= ストレージバックエンドを管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージバックエンドは、ESXiホストがデータストレージに使用するシステムです。



== ストレージの検出

ストレージバックエンドの検出は、スケジュールされた検出によってストレージの詳細が更新されるのを待たずにオンデマンドで実行できます。

ストレージバックエンドを検出するには、次の手順を実行します。

.手順
. vSphere Clientにログインします。
. ショートカットページで、プラグインセクションの* NetApp ONTAP tools *を選択します。
. ONTAP toolsの左側のペインで、*[Storage backends]*に移動し、ストレージバックエンドを選択します。
. 縦の省略記号メニューを選択し、*ストレージの検出*を選択します。


進捗状況は、[最近のタスク]パネルで追跡できます。



== ストレージバックエンドの変更

ストレージバックエンドを変更するには、このセクションの手順を実行します。

. vSphere Clientにログインします。
. ショートカットページで、プラグインセクションの* NetApp ONTAP tools *を選択します。
. ONTAP toolsの左側のペインで、*[Storage backends]*に移動し、ストレージバックエンドを選択します。
. クレデンシャルまたはポート名を変更するには、縦の省略記号メニューを選択し、*[変更]*を選択します。進捗状況は、[最近のタスク]パネルで追跡できます。


ONTAP tools Managerを使用してグローバルONTAPクラスタに対して変更処理を実行するには、次の手順を実行します。

. WebブラウザからONTAP Tools Managerを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者のクレデンシャルを使用してログインします。
. サイドバーからストレージバックエンドを選択します。
. 変更するストレージバックエンドを選択します。
. 垂直楕円メニューを選択し、*修正*を選択します。
. クレデンシャルまたはポートを変更できます。ストレージバックエンドを変更するには、*[Username]*と*[Password]*を入力します。




== ストレージバックエンドの削除

ストレージバックエンドを削除する前に、ストレージバックエンドに接続されているすべてのデータストアを削除する必要があります。ストレージバックエンドを削除するには、次の手順を実行します。

. vSphere Clientにログインします。
. ショートカットページで、プラグインセクションの* NetApp ONTAP tools *を選択します。
. ONTAP toolsの左側のペインで、*[Storage backends]*に移動し、ストレージバックエンドを選択します。
. 垂直の楕円メニューを選択し、*削除*を選択します。ストレージバックエンドにデータストアがないことを確認します。進捗状況は、[最近のタスク]パネルで追跡できます。


ONTAP tools Managerを使用して、グローバルONTAPクラスタの削除処理を実行できます。

. WebブラウザからONTAP Tools Managerを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者のクレデンシャルを使用してログインします。
. サイドバーから* Storage backends *を選択します。
. 削除するストレージバックエンドを選択してください
. 垂直の楕円メニューを選択し、*削除*を選択します。




== ストレージバックエンドのドリルダウンビュー

ストレージバックエンドページには、すべてのストレージバックエンドが表示されます。ストレージの検出、変更、および削除の処理は、クラスタ内の個 々 の子SVMではなく、追加したストレージバックエンドに対して実行できます。

ストレージバックエンドの親クラスタまたは子クラスタを選択すると、コンポーネントの全体的な概要が表示されます。親クラスタを選択すると、処理ドロップダウンからストレージの検出、変更、削除の各処理を実行できます。

概要ページには、次の詳細が表示されます。

* ストレージバックエンドのステータス
* 容量情報
* VMに関する基本情報
* ネットワークのIPアドレスやポートなどのネットワーク情報。子SVMの場合、情報は親ストレージバックエンドと同じになります。
* ストレージバックエンドに対して許可および制限された権限。子SVMの場合、情報は親ストレージバックエンドと同じになります。権限はクラスタベースのストレージバックエンドでのみ表示されます。SVMをストレージバックエンドとして追加すると、権限の情報は表示されません。
* SVMまたはクラスタに対してDisaggregatedプロパティが「true」に設定されている場合、ASA R2クラスタのドリルダウンビューに[Local Tiers]タブは表示されません。
* ASA R2 SVMシステムでは、容量ポートレットは表示されません。容量ポータルは、SVMまたはクラスタに対してDisaggregatedプロパティが「true」に設定されている場合にのみ必要です。
* ASA R2 SVMシステムの場合は、[基本情報]セクションにプラットフォームタイプが表示されます。


[Interface]タブには、インターフェイスに関する詳細情報が表示されます。

[ローカル階層]タブには、アグリゲートリストに関する詳細情報が表示されます。
